source 'https://github.com/CocoaPods/Specs'

platform :ios, '9.0'
use_frameworks!

# Add Application pods here
def app_pods
end

# Add Testing pods here
def testing_pods
end

target 'XLProjectName' do
    app_pods
end

target 'XLProjectName-Staging' do
    app_pods
end

target 'Tests' do
  testing_pods
end

target 'UITests' do
    testing_pods
end

post_install do |installer|
    puts 'Setting swift version to 3.0'
    installer.pods_project.build_configurations.each do |build_conf|
        build_conf.build_settings['SWIFT_VERSION'] = '3.0'
    end

    puts 'Removing static analyzer support'
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Qunused-arguments -Xanalyzer -analyzer-disable-all-checks"
        end
    end
end
